version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/travel-zip-deploy
    overwrite: yes

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root

  ApplicationStart:
    - location: scripts/stop.sh
      runas: root